spring.application.name=auth-service

server.port=8081

# Подключение к PostgreSQL в Docker
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/auth_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Логирование для отладки БД
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG
spring.datasource.hikari.maximum-pool-size=1