spring.application.name=auth-service
server.port=${PORT:8081}

# Подключение к PostgreSQL через переменные окружения
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:auth_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Логирование
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG
spring.datasource.hikari.maximum-pool-size=1
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# JWT токен (RSA асимметричное шифрование)
jwt.expiration=3600000
jwt.private-key=${JWT_PRIVATE_KEY:classpath:keys/private.key}
jwt.public-key=${JWT_PUBLIC_KEY:classpath:keys/public.key}