spring.application.name=notification-service

server.port=8086
# Этот сервис, как и product, работает с MongoDB.
# База notification_db создастся автоматически в Docker при первом запросе.
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=notification_db