spring.application.name=api-gateway
server.port=8080

jwt.public-key=${JWT_PUBLIC_KEY:file:.secrets/dev/public.key}


# Gateway routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=http://${PRODUCT_SERVICE_HOST:localhost}:${PRODUCT_SERVICE_PORT:8083}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/products/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuth

spring.cloud.gateway.routes[2].id=user-service
spring.cloud.gateway.routes[2].uri=http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/users/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuth

spring.cloud.gateway.routes[3].id=inventory-service
spring.cloud.gateway.routes[3].uri=http://${INVENTORY_SERVICE_HOST:localhost}:${INVENTORY_SERVICE_PORT:8084}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/inventory/**
spring.cloud.gateway.routes[3].filters[0]=JwtAuth

spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=http://${ORDER_SERVICE_HOST:localhost}:${ORDER_SERVICE_PORT:8085}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/orders/**
spring.cloud.gateway.routes[4].filters[0]=JwtAuth

spring.cloud.gateway.routes[5].id=notification-service
spring.cloud.gateway.routes[5].uri=http://${NOTIFICATION_SERVICE_HOST:localhost}:${NOTIFICATION_SERVICE_PORT:8086}
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/notifications/**
spring.cloud.gateway.routes[5].filters[0]=JwtAuth

# OpenAPI routes
spring.cloud.gateway.routes[6].id=auth-openapi
spring.cloud.gateway.routes[6].uri=http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}
spring.cloud.gateway.routes[6].predicates[0]=Path=/v3/api-docs/auth
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/v3/api-docs/auth,/v3/api-docs

spring.cloud.gateway.routes[7].id=user-openapi
spring.cloud.gateway.routes[7].uri=http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8082}
spring.cloud.gateway.routes[7].predicates[0]=Path=/v3/api-docs/users
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/v3/api-docs/users,/v3/api-docs

spring.cloud.gateway.routes[8].id=product-openapi
spring.cloud.gateway.routes[8].uri=http://${PRODUCT_SERVICE_HOST:localhost}:${PRODUCT_SERVICE_PORT:8083}
spring.cloud.gateway.routes[8].predicates[0]=Path=/v3/api-docs/products
spring.cloud.gateway.routes[8].filters[0]=RewritePath=/v3/api-docs/products,/v3/api-docs

spring.cloud.gateway.routes[9].id=inventory-openapi
spring.cloud.gateway.routes[9].uri=http://${INVENTORY_SERVICE_HOST:localhost}:${INVENTORY_SERVICE_PORT:8084}
spring.cloud.gateway.routes[9].predicates[0]=Path=/v3/api-docs/inventory
spring.cloud.gateway.routes[9].filters[0]=RewritePath=/v3/api-docs/inventory,/v3/api-docs

spring.cloud.gateway.routes[10].id=order-openapi
spring.cloud.gateway.routes[10].uri=http://${ORDER_SERVICE_HOST:localhost}:${ORDER_SERVICE_PORT:8085}
spring.cloud.gateway.routes[10].predicates[0]=Path=/v3/api-docs/orders
spring.cloud.gateway.routes[10].filters[0]=RewritePath=/v3/api-docs/orders,/v3/api-docs

spring.cloud.gateway.routes[11].id=notification-openapi
spring.cloud.gateway.routes[11].uri=http://${NOTIFICATION_SERVICE_HOST:localhost}:${NOTIFICATION_SERVICE_PORT:8086}
spring.cloud.gateway.routes[11].predicates[0]=Path=/v3/api-docs/notifications
spring.cloud.gateway.routes[11].filters[0]=RewritePath=/v3/api-docs/notifications,/v3/api-docs

# Swagger UI
springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/auth

springdoc.swagger-ui.urls[1].name=User Service
springdoc.swagger-ui.urls[1].url=/v3/api-docs/users

springdoc.swagger-ui.urls[2].name=Product Service
springdoc.swagger-ui.urls[2].url=/v3/api-docs/products

springdoc.swagger-ui.urls[3].name=Inventory Service
springdoc.swagger-ui.urls[3].url=/v3/api-docs/inventory

springdoc.swagger-ui.urls[4].name=Order Service
springdoc.swagger-ui.urls[4].url=/v3/api-docs/orders

springdoc.swagger-ui.urls[5].name=Notification Service
springdoc.swagger-ui.urls[5].url=/v3/api-docs/notifications

management.endpoints.web.exposure.include=health,info,gateway,prometheus
management.endpoint.gateway.enabled=true

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
