spring.application.name=api-gateway
server.port=8080

jwt.public-key=${JWT_PUBLIC_KEY:classpath:keys/public.key}

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=http://${PRODUCT_SERVICE_HOST:localhost}:${PRODUCT_SERVICE_PORT:8083}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/products/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuth

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=TRACE